WIP fixed discovery service and security-doc errors
kostua16/UNC_2020_MS_TLT pull request #190
Opened 2021-03-19 13:46 UTC by Spec163

2021-03-19 13:48 UTC, Spec163 commented
/lint

2021-03-19 13:51 UTC, kostua16 commented
Depends on #191 due to build failure for commit 6fe20a490eab0d4aaaf2a9ad5075c5e1fdafad1a

2021-03-19 15:03 UTC, kostua16 commented
Depends on #195 due to build failure for commit 6fe20a490eab0d4aaaf2a9ad5075c5e1fdafad1a

2021-03-20 14:09 UTC, Spec163 commented
я сломал тесты

2021-03-21 07:28 UTC, kostua16 commented
Depends on #200 due to build failure for commit b65ca5395db26caa5281782cb29d94b0768ae394

2021-03-23 13:04 UTC, kostua16 commented
Depends on #207 due to build failure for commit 8402a60460ffdd31d3b0237be0cb54af996d0079

2021-03-23 15:45 UTC, kostua16 commented
Depends on #209 due to build failure for commit bce90f75293d1ed80dcabcf34947025f386b040a

2021-03-23 15:55 UTC, kostua16 commented
Depends on #211 due to build failure for commit bce90f75293d1ed80dcabcf34947025f386b040a

2021-03-23 16:04 UTC, kostua16 commented
Depends on #212 due to build failure for commit bce90f75293d1ed80dcabcf34947025f386b040a

2021-03-23 16:07 UTC, kostua16 commented
Depends on #213 due to build failure for commit e2c3650e3cb0395d227fafd7204813f9c5368c2b

2021-03-26 07:21 UTC, kostua16 commented
Depends on #215 due to build failure for commit 9b0376a8842d2aad7299096d061aefae43f2feae

2021-03-26 07:31 UTC, kostua16 commented
Need to fix build for "client-ui" module by creating empty file "src/main/java/.gitkeep".

Error:  Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.8.0.2131:sonar (default) on project client-ui: The directory '/home/runner/work/UNC_2020_MS_TLT/UNC_2020_MS_TLT/client-ui/src/main/java' does not exist for Maven module nc.unc.cs:client-ui:jar:0.0.1-SNAPSHOT.

2021-03-26 15:12 UTC, kostua16 commented
Build successfully completed for commit d10379a853055a77949d60d9ecbb0e8394b5f681

2021-03-26 15:56 UTC, kostua16 commented on services/tax/src/main/java/nc/unc/cs/services/tax/confogurations/SecurityConfig.java
> +}
move to common module as it duplicated in each affected service

2021-03-26 15:56 UTC, kostua16 commented on services/passport/src/main/java/nc/unc/cs/services/passport/confogurations/SecurityConfig.java
> +}
to common module

2021-03-26 15:56 UTC, kostua16 commented on services/logging/src/main/java/nc/unc/cs/services/logging/confogurations/SecurityConfig.java
> +}
to common module

2021-03-26 15:56 UTC, kostua16 commented on services/gibdd/src/main/java/nc/unc/cs/services/gibdd/confogurations/SecurityConfig.java
> +}
to common module

2021-03-26 15:56 UTC, kostua16 commented on services/communal/src/main/java/nc/unc/cs/services/communal/confogurations/SecurityConfig.java
> +}
to common module

2021-03-26 15:56 UTC, kostua16 commented on services/bank/src/main/java/nc/unc/cs/services/bank/confogurations/SecurityConfig.java
> +}
to common module

2021-03-26 15:56 UTC, kostua16 commented on pom.xml
> +          <argLine>${spring.runner.args} ${argLine}</argLine>
> @{argLine}

is a special vadiable [@{argLine} meaning](https://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#argLine)

2021-03-26 15:56 UTC, kostua16 commented on pom.xml
> +          <argLine>${spring.runner.args} ${argLine}</argLine>
>${spring.runner.args} - is correct change

2021-03-27 09:16 UTC, kostua16 commented
Depends on #227 due to build failure for commit 53ff96be50ffed792973ed353eade0dc92b4d618

2021-03-27 09:33 UTC, kostua16 commented
Build successfully completed for commit 788da2e084944c3a69b17b9ee3b786fb0bc5a78f

2021-03-29 09:43 UTC, kostua16 requested changes

2021-03-29 09:43 UTC, kostua16 commented on pom.xml
> +          <argLine>${spring.runner.args} ${argLine}</argLine>
still not fixed

2021-03-29 09:43 UTC, kostua16 commented on services/common/src/main/java/nc/unc/cs/services/common/configurations/SecurityConfig.java
> +public class SecurityConfig extends WebSecurityConfigurerAdapter {
is it removed from other services?

2021-03-29 09:50 UTC, kostua16 requested changes

2021-03-29 09:50 UTC, kostua16 commented on client-ui/src/services/communal/communal-service.js
> +                    console.log('RESPONSE REGISTRATION: ', response)
todo: add UI feedback for the action call.

2021-03-29 09:50 UTC, kostua16 commented on client-ui/src/services/communal/property-service.js
> +                    console.log('REGISTRATE PROPERTY: ', response)
todo: add UI feedback

2021-03-29 09:50 UTC, kostua16 commented on client-ui/src/services/tax/tax-service.js
> +const API_URL = 'http://localhost:8082/tax'
todo: switch to node vue-dev server and will the property automatically from the configuration

2021-03-30 10:52 UTC, Spec163 commented on services/common/src/main/java/nc/unc/cs/services/common/configurations/SecurityConfig.java
> +public class SecurityConfig extends WebSecurityConfigurerAdapter {
+

2021-03-30 11:10 UTC, kostua16 commented
Build successfully completed for commit ce0f250c18e8d7eca3ac4f6281c94937103bea37

2021-04-02 14:38 UTC, kostua16 approved these changes

2021-04-02 14:39 UTC, merged