WIP price lists
kostua16/UNC_2020_MS_TLT pull request #264
Opened 2021-04-05 15:15 UTC by Spec163

2021-04-05 15:18 UTC, kostua16 commented
Depends on #266 due to build failure for commit fcc5239c6385807dd8d46355c1b5cd8c13ad10cb

2021-04-05 15:22 UTC, kostua16 commented
Build successfully completed for commit 6a990be6ff346cd71cecf3c64e3696fd399201e2

2021-04-05 15:32 UTC, kostua16 commented
Build successfully completed for commit 8c82288a5b7e2557b14e92c6cec989986f08b6e5

2021-04-05 15:35 UTC, kostua16 commented
Build successfully completed for commit 8c82288a5b7e2557b14e92c6cec989986f08b6e5

2021-04-05 15:36 UTC, kostua16 commented
Build successfully completed for commit 8c82288a5b7e2557b14e92c6cec989986f08b6e5

2021-04-05 16:24 UTC, kostua16 commented
Build successfully completed for commit 85e99d0a553bb9662d60bb713674dec7ed338952

2021-04-05 16:31 UTC, kostua16 commented
Build successfully completed for commit 9f836ca99421db9018e20aa84902d80bdf53425c

2021-04-05 16:34 UTC, kostua16 commented
Build successfully completed for commit 51d0feef8107f6c1b1b0b441be8a8189f01b363c

2021-04-05 16:35 UTC, kostua16 commented
Build successfully completed for commit 51d0feef8107f6c1b1b0b441be8a8189f01b363c

2021-04-06 07:34 UTC, kostua16 commented
Build successfully completed for commit 51d0feef8107f6c1b1b0b441be8a8189f01b363c

2021-04-06 19:54 UTC, kostua16 commented
Build successfully completed for commit 9d5c3f183f367b4e3bbb9e1b8d0e92a11533236f

2021-04-07 05:49 UTC, kostua16 commented
Build successfully completed for commit 729023380634bd5085dcfbe825e2863d5e4e9e6c

2021-04-07 13:53 UTC, kostua16 commented
Build successfully completed for commit f64cdb7b16ad14b8699a7d837e15a5a8ad3fe99f

2021-04-07 13:54 UTC, kostua16 requested changes

2021-04-07 13:54 UTC, kostua16 commented on services/bank/src/docs/asciidoc/bank.adoc
> +Konstantin Leontiev;
Correct author

2021-04-07 13:54 UTC, kostua16 commented on services/gibdd/src/docs/asciidoc/gibdd.adoc
>  Konstantin Leontiev;
Correct Author

2021-04-07 15:41 UTC, kostua16 commented
Build successfully completed for commit 74530d5b290180a5a911712188f8d5de77babfcb

2021-04-07 15:42 UTC, Spec163 commented on services/gibdd/src/docs/asciidoc/gibdd.adoc
>  Konstantin Leontiev;
В этом файле не стал менять, тк ГИБДД это сервис кураторов

2021-04-16 12:13 UTC, kostua16 commented
Build successfully completed for commit 66508d8ecef1d96862ce1b293fdeda586e6a3fe6

2021-04-16 12:22 UTC, kostua16 approved these changes

2021-04-16 12:23 UTC, merged